### ISSUE TITLE
Does 'useFileTransport' work correctly?

### ISSUE THREAD

**Issue by voshkin** [yarcode/yii2-mailgun-mailer#3]
I've used the 'useFileTransport' setting, but i receive empty mails permanently. What do you mean about this? (When i turning off the 'useFileTransport', my mailgun account is working fine)

**Comment by russianlagman** [comment]
Mailgun is not called when you set useFileTransport => true. Check the runtime/mail instead.

**Comment by voshkin** [comment]
it looks like you misunderstand me. When i use 'useFileTransport' i see empty mails in the runtime directory (0 bytes, 0 lines). When i'm turning off the  'useFileTransport', my mailgun account is working fine.

**Comment by russianlagman** [comment]
Now I see... I think we need to implement this method https://github.com/yarcode/yii2-mailgun-mailer/blob/master/src/Message.php#L268

**Comment by russianlagman** [comment]
fixed in **1.1.3**
